[package]
name = "ultimate-xo-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
axum-macros = "0.4.2"
serde = { version = "1.0.213", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
